# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpForm(object):
    def setupUi(self, HelpForm):
        HelpForm.setObjectName("HelpForm")
        HelpForm.resize(400, 300)
        self.text_browser = QtWidgets.QTextBrowser(HelpForm)
        self.text_browser.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.text_browser.setObjectName("text_browser")

        self.retranslateUi(HelpForm)
        QtCore.QMetaObject.connectSlotsByName(HelpForm)

    def retranslateUi(self, HelpForm):
        _translate = QtCore.QCoreApplication.translate
        HelpForm.setWindowTitle(_translate("HelpForm", "Помощь"))
